AWSTemplateFormatVersion: 2010-09-09
Description: Create SNS::TopicPolicy using private resource provider from CFN stack
Resources:
  SNSAccessPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: SNSTopicEmail
        Statement:
          - Action:
              - 'SNS:Publish'
              - 'SNS:GetTopicAttributes'
              - 'SNS:SetTopicAttributes'
              - 'SNS:DeleteTopic'
              - 'SNS:Subscribe'
              - 'SNS:ListSubscriptionsByTopic'
              - 'SNS:Publish'
              - 'SNS:Receive'
            Effect: Allow
            Principal:
              AWS: '123456789'
            Condition:
              StringEquals:
                'AWS:SourceOwner': '123456789'
            Resource: 'arn:aws:sns:us-east-1:123456789:my-topic1'
      Topics:
        - 'arn:aws:sns:us-east-1:123456789:my-topic1'
        - 'arn:aws:sns:us-east-1:123456789:my-topic199'
